import type { Venue } from "./types";

export const venues: Venue[] = [
  {
    id: "gangil-myeongil",
    name: "강일·명일 테니스장",
    area: "강동구",
    openRules: [
      {
        id: "gangil-myeongil-15",
        label: "매월 15일 10:00",
        dayOfMonth: 15,
        hour: 10,
        minute: 0,
        targetPeriod: "다음 예약 회차",
      },
    ],
    links: [
      {
        id: "gangil-myeongil-main",
        label: "예약 사이트",
        category: "general",
        url: "https://gdgd.igangdong.or.kr",
        source: "강동구",
      },
    ],
  },
  {
    id: "nudge-tennis",
    name: "넛지 테니스",
    area: "네이버 예약",
    openRules: [
      {
        id: "nudge-15",
        label: "매월 15일 09:00-10:00",
        dayOfMonth: 15,
        hour: 9,
        minute: 0,
        windowEnd: { hour: 10, minute: 0 },
        targetPeriod: "월중 오픈",
      },
      {
        id: "nudge-30",
        label: "매월 30일 09:00-10:00",
        dayOfMonth: 30,
        hour: 9,
        minute: 0,
        windowEnd: { hour: 10, minute: 0 },
        targetPeriod: "월말 오픈",
      },
    ],
    links: [
      {
        id: "nudge-main",
        label: "네이버 예약",
        category: "general",
        url: "https://map.naver.com/p/entry/place/1720282889?c=15.00,0,0,0,dh&placePath=/ticket&fromPanelNum=1&additionalHeight=76&timestamp=202606031831&locale=ko&svcName=map_pcv5",
        source: "네이버",
      },
    ],
  },
  {
    id: "jangchung",
    name: "장충테니스장",
    area: "중구",
    openRules: [
      {
        id: "jangchung-10",
        label: "매월 10일 10:00",
        dayOfMonth: 10,
        hour: 10,
        minute: 0,
        targetPeriod: "다음달 16일-31일",
      },
      {
        id: "jangchung-25",
        label: "매월 25일 10:00",
        dayOfMonth: 25,
        hour: 10,
        minute: 0,
        targetPeriod: "다음달 1일-15일",
      },
    ],
    links: [
      {
        id: "jangchung-court-9-weekend",
        label: "9번 코트",
        court: "9번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260522162551029150&currentPage=1",
        source: "서울시",
      },
      {
        id: "jangchung-court-8-weekend",
        label: "8번 코트",
        court: "8번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260522162317428453&currentPage=1",
        source: "서울시",
      },
      {
        id: "jangchung-court-2-weekend",
        label: "2번 코트",
        court: "2번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260522160816894084&currentPage=3",
        source: "서울시",
      },
      {
        id: "jangchung-court-3-weekend",
        label: "3번 코트",
        court: "3번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260522161342981234&currentPage=3",
        source: "서울시",
      },
      {
        id: "jangchung-court-7-weekend",
        label: "7번 코트",
        court: "7번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260522162105102385&currentPage=3",
        source: "서울시",
      },
      {
        id: "jangchung-court-4-weekend",
        label: "4번 코트",
        court: "4번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260522161836086246&currentPage=3",
        source: "서울시",
      },
    ],
  },
  {
    id: "gwangnaru-hangang",
    name: "광나루한강테니스장",
    area: "강동구",
    openRules: [
      {
        id: "gwangnaru-1",
        label: "매월 1일 00:00",
        dayOfMonth: 1,
        hour: 0,
        minute: 0,
        targetPeriod: "월간 오픈",
      },
    ],
    links: [
      {
        id: "gwangnaru-court-6-weekend",
        label: "6번 코트",
        court: "6번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530093002938259&currentPage=3",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-3-weekend",
        label: "3번 코트",
        court: "3번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530092536577355&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-4-weekend",
        label: "4번 코트",
        court: "4번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530092708693861&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-7-weekend",
        label: "7번 코트",
        court: "7번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530093131407904&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-5-weekend",
        label: "5번 코트",
        court: "5번",
        category: "weekend_holiday",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530092831620884&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-3-evening",
        label: "3번 코트",
        court: "3번",
        category: "weekday_evening",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530091707418356&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-5-evening",
        label: "5번 코트",
        court: "5번",
        category: "weekday_evening",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530092042750604&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-7-evening",
        label: "7번 코트",
        court: "7번",
        category: "weekday_evening",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530092354454732&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-6-evening",
        label: "6번 코트",
        court: "6번",
        category: "weekday_evening",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530092220481323&currentPage=1",
        source: "서울시",
      },
      {
        id: "gwangnaru-court-4-evening",
        label: "4번 코트",
        court: "4번",
        category: "weekday_evening",
        url: "https://yeyak.seoul.go.kr/web/reservation/selectReservView.do?rsv_svc_id=S260530091905095320&currentPage=1",
        source: "서울시",
      },
    ],
  },
  {
    id: "yangjae",
    name: "양재 테니스장",
    area: "서초구",
    openRules: [
      {
        id: "yangjae-1",
        label: "매월 1일 09:00",
        dayOfMonth: 1,
        hour: 9,
        minute: 0,
        targetPeriod: "월간 오픈",
      },
    ],
    links: [
      {
        id: "yangjae-main",
        label: "네이버 예약",
        category: "general",
        url: "https://booking.naver.com/booking/10/bizes/210031",
        source: "네이버",
      },
    ],
  },
];
